### ISSUE TITLE
Movecraft-Towny Movecraft-Cannons Compat

### ISSUE THREAD

**Issue by Garrett119** [APDevTeam/Movecraft-Towny#3]
While these two plugins appear compatible and do not throw errors in console when loaded together, Movecraft-Cannons does not work (moving cannons unregister when moved) when Movecraft-Towny is enabled. Confirmed this by booting it up without towny or movecraft-towny enabled, and there were no problems.

**Comment by TylerS1066** [comment]
Interesting, which server software and MC version are you running?

The above issue is where somebody found it worked on purpur and not paper, so that may mask this issue if they are the same problem.

**Comment by TylerS1066** [comment]
It appears that both this and Movecraft-WorldGuard have problems, I'll see if I can upgrade my test server to 1.14 and test it.

https://github.com/APDevTeam/Movecraft-WorldGuard/issues/4

**Comment by TylerS1066** [comment]
@Garrett119 I can not seem to reproduce this on my 1.14.4 paper test server with the latest released versions.

I have the cannons disappear when I rotate but work properly on translation, is this the symptom you have?

**Comment by TylerS1066** [comment]
I believe this may have been fixed in one of the updates to Movecraft-Cannons.  Please try it out and if the problem still exists only when you have the addons installed, please reopen this.
